workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: bd9a4095-a52d-400f-ac40-27da4241deea
        APP_STORE_CONNECT_KEY_IDENTIFIER: 7DNXNP99C5
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhXYk5kZjVPbzRnQzJfdFdacnI5QXhhT29ocGM3RWc3S1V6RUgzcHRQUTc5SFJXQXoxaWdtZ0Zza3gwcnVPZ3gyakw0RFVob2F1T2JJb1JjLXVETlJTMWVEbHV6WC0tUjRzQU9IYmd5SThaaWZSbEp5c0xTRGhYNk16LWRqcDF0aVFDWmRBTVVxVmhoRjdfcDNKR0FCaElxTFM0bkhHbmtmSnVWT3pMUFhPV3hKbjM2TktOblR6VW5FbUxyTlZHdVZpc0xUOWRnc3EzU2pnbFdSbzVLallsMEhzOS1BQmlCZjVBNmFuM3UzVTRXb3dkRFJuVjBlNU1yejBQYnV5cnU1YW9FbzJwSWR3YkpCN3lIVEhCM0JFb0J3UXZSUE1Mek1tTTE1Q3VXSXowdlFBbENHZ1h5ektnOEgxTU9odk9PdXkwQ0U5M0ItNzFnNEhnNHU1RHdOODRYQ2QtTFJPS0lKcTBQS04taDJzQUV2ZjBSLTZNRnlGVE1zMWpKUmExV0toN0pEbHEwNmZXQ3NPMUtwSEFrY016TXcxaTdHQlQ3RndfUk1YSTY4LTNxaE9jWT0=)
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhXYk5ka1pkYkpIV3JXUGw3d1JMQVp0NnhZN3BoLWQwbkhJak9icURhQkJrcC1Qak94SGpVcUVNTGIzYXljeDNQMEYtbE1fY1lYQlJ2ZTliSXJRQzdXYTk5NUtWNVdlUmhocHFKcXdJcldaZWJZRlh6cHRHTUUxWU1JaFhlNFFyREJOcDRHN3lKcG1WTGU5aGRWbTRYUDJXb1lvSmlyVm9OTVBRRHZaY3Q1c1RuTlhUNnNBZHk0cmxGRlZTUWpSN2lJcF9VOTZXSEJ6RDIyOE9Mc3BmRW9JUUZZdkhjd3phQ2FXQmNMOGVWOXIzQUJ1V2ZqSGFfZjhhTmUxWk5leVlHSHpIWjJ4N2o1NVktRTVWeEdxdE9GekM5THA1MWJROHJseVY1ZWxSVmdRSEdhaDExeDZkQ01UTzRuekc1MnlpZzFia2d1eGpmTjBVenFkcjYtTFJiZmpIMXc3WktGZmdSaVh4bmVTQXVKdW5IeW5QanJicEd6Q2dOUk1Ud05ZQllsNU9rVHJpTTczRUFjUVV5SnFvc0JBWFIwOVlnUVBYckZwVWc1ZGYwYzZWN2hjWExjam9GWkpCbkJfUU9fVjBwRGhDNU9SdFFhVFZKNkdZYU5JbVBhdTlJM0RIeFVtSnUtZVFGOFRrMndmd2luWVI4cG1LelFiMHZkWVh6Z1E4T3o0dHBYZWcyZTB0ckxBN181VkJ1bm5QdHJOQWNVU0tVQVpXMjVkaUdMeFAwdnpfYzh6MVdody1ZRnFBLTcwXzZVZXl2UWxpQ2ZSaHVoVTYtNjBac0NjN3JJQmlhU2xRWGxYNGxCUnFmbmp5ZnVNV2hrQmhNYVBmb2NTV1JNeXg1cmE1WGFrRzc4TE1UOG0taVlwa0pwUl9pLXpzaTZ1YjJMamVBT1p5SmhiRUtZUEhFRzlDM0F4RnBaQXVjWGtQLTRiYkhkOXRxUE1vSTF4dFdfT2FTcl9Pa3BxWUtGME9fOTZmY3diOTRmZHNLWHdIOHBjUDlTcHo2Z24yVFJqYVhyZWY0OVN2U29SOUZZNDdUdk9DVlE4Mm1wZGdvajBGeXJsRjNnVVQ5eVpjazAwRGNfVFRpalZFMm9SZWx4QnBlY09SMFBKdEFNSS1Ib2pLWXZOLVJ1ODAyaHdSZ2dIQ3VVNnRLN1k2ZnNvcXNrQUxCeFVQbzRHXy0zRmtVTlJYek1UeUl1VjVQakZfZm51NUh4cGRLRVJsczBPNjdsTXQ4WTEtMlduTFFIV1BZV29mcFhGVS0xZnpaelJNcVpEUENHOVNJY0laRG9iSThTRzk4QU9FSmNCOWt1bFQxeUZxXzVjWGJua1p4bEtzYkVZSGsyTnUwS0xwcXNBbnpHZGZVaFpqQ09YdEROcDljcER6UDZnS19vVU1kZkFHeDhVRlZlS3hkQ1dsTkZxV0ZSMV9jMEJKelVXS0tvMGxURzR0U3VXTFFkUlVNRHB3MFc2ay1WN3ViUlpHV0t5c0hDWkxvMGJKNTB3WXNKd2wtQS16VnByd2dpaUhKM3Y2UnFoallDQjI4OHQzbDQweWNUb2h6YklrRzB1d0tFdkdpZnk1amQ3Rzd0eTFJYVBybjlMTmdQcktCdnBHeklVV25ybmd1QWZpMHlUZGpVUHQ5YlhUeWl2eG15d3FubTVOVnYtSmRoaV9oNGVNRUJHME96bDRCaVBQWVg1Nkt2aEIxUHhZODB3NHJOUkRyT2N6UC03M3lsSlczVzhoTHowM29sMjFZUGRJbFBVa0xwN1p1MXRSV1NhV1UxU3NaQWRWaXY2TW5Rdkg0dkcwZmZlM0Z5M3p0d3lRSW92akIxSnlscE9ENG1sMURFaTJxNG1zTWtVbjJ3UnVNcGV6R3JWa1l3dTU1TTNmbjNDT2lUR2ZtcWYySjRkZHNKTEpiaDBCa2RDX0JicmNxRS1VUHN4c1BKWHFVaU9xSjBqTHBpOHFyTkpKQVZCMVI0YTJ3dEs1bEVlbm5EeU1jWjNBdjZDX0djMkdKdFNxTV80WFU4LTlfZU9wZzhsWTZnR0RPenpweGw2b09RcTkwX0ZUSDJhanZpdENyZk9WeW00bFh2WlpidE5EdFBkRXVlY1dFT1hnUERlb3BETHprbnREUV9Wd044N2dMY0RoYXhvNUwyRWJzeTNUb2htUlBibWNmWmZmdTBTVmljZ0MyNjRiZUxCdWtNb1RGYms3UWRBQVo5NklSZWZJWVMxd1VSTzdCUnQ0TUMza3hYN2QwWFlhOUhWUFJ2aFRQVFdhRjg1WW5kcEhvYm84RDJOR2RaeV9lYjROVWxQUWc5bW83WV9nXzlzR3ptNHo5ck16RW9zUURrMk1fOWZ0NHpLMHR4MXkwTzFKM25xWjlPOXZPcVBMRHNncm9KdlhydWlidERDaUt2ZF9oUGppVDJtNE54OEpjYXp2OE9kVmszbFBhT1ZUSnVsUXkyTHlabUV5eTlTdzBmZ0R2UXpPQTBTaU9Ja2FwSmQ3eGd5YTgzMEY2X3RtOXI4SjBUSUNUd2dONmpWUFRXZXFpaC1KajZ1eXl0anhZRnNJTDlGZnFSVzNoVVJtN0R4N2F3WWg1T3hRYkVkeVFpb3RiZ2R1OGlTdHlNeEpMWWZvZWp3ZG5rdmViUnR3RDV5bjlScmZvSEJJdno0VzRUQ3ZBUWQzOXZSU24yMlhmTXpTYm9rc3lIUkVnbkFxTEJpbmkxd1B3UjNWTUxOQ3NzbUhGWW1ta29kSWFtaUsxd2JsZk13ZWk0aVZEdEYwc0hLY2JMVnJsZkhHNUQyQmtUaTl2cHp0aXhGSkxXdGYtQUJ4TDg1UUpySU15WEEyVkVTWTNYOGZDOWdjSUEwcll2VFAyY3RUQlpRQ2hUOWtreExJSWJXeDZGMjdIUW56a2dPdWdCckdqMF96ZVpKcGExd1FNdi0yNFp2WmpMam5uWHJ1OHBseW5fbTRWenYzSU5QQ185NlVyMGZHMThJOTU4eUgzUWJMSU96aXoxVU5GVGo1VXVsVEU2ekRTc0JRQllzOGN5TUFnbWE1ZVBaeXI1Y3RjY2JjWmZjbXFCM0dNRllRMlN6emhfZmVW)
        BUNDLE_ID: "net.alazzani"
        APP_STORE_APP_ID: 1575355708
        XCODE_PROJECT: "alazzani.xcworkspace"
        XCODE_SCHEME: "alazzani"
        APPLE_ID: Encrypted(Z0FBQUFBQmc1YXRBZENMc0hrT1RFTEZGemxxY0Jac1gzNHE1alJKVDU0MUZSbTlieVZ4eVRmYzRSTTdod2VCZ1lXS2Vjc0RGbTVoYlJ3U25nZU0yRUM1TGszdm1CSjJGTUJvRU02empRNzQ0VzBXTnZJTy1WUFE9)
        APP_SPECIFIC_PASSWORD: Encrypted(Z0FBQUFBQmc1YXRQdmMydlo5NTRSbmtYOHk3SEF3eFhxVk5aSU5nZWtmdjMtWkdQd1RvNlhTeURvUWJ4MXNHRTg5MWZDSDBjVlo0OTVFam9BSnZfaGk3YW9LalBUVFNPWExwUjVhR3M2MXMzbURiUGp1WXFGaEE9)
      node: 16.2.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          yarn install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Increment build number
        script: |
          #!/bin/sh
          set -e
          set -x
          cd $FCI_BUILD_DIR/ios
          # agvtool new-version -all $(($BUILD_NUMBER + 1))
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$FCI_BUILD_DIR/ios/$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
